steps:
- name: gcr.io/cloud-builders/gcloud
  dir: app
  args:
  - kms
  - decrypt
  - --ciphertext-file=mmc-dppo-6cd361f07742.json.enc
  - --plaintext-file=mmc-dppo-6cd361f07742.json
  - --location=global
  - --keyring=hikma-key-ring
  - --key=hikma-crypto-key
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA',
          '--build-arg', 'app_env_arg=prod',
          '--build-arg', 'credential_file_arg=mmc-dppo-6cd361f07742.json',
          '--build-arg', 'db_instance_arg=${_DB_INSTANCE}',
          '--build-arg', 'commit_sha_arg=$COMMIT_SHA',
          '--build-arg', 'db_password_arg=${_DB_PASSWORD}',
          '--build-arg', 'db_name_arg=${_DB_NAME}',
          '--build-arg', 'photos_storage_bucket_arg=${_PHOTOS_STORAGE_BUCKET}',
          '--build-arg', 'exports_storage_bucket_arg=${_EXPORTS_STORAGE_BUCKET}',
          '.' ]
  dir: app
- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=us-east1-b', 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster']
  args: ['set', 'image', 'deployment/hikma-health-backend',
        'hikma-health-backend=gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA']
images:
- 'gcr.io/$PROJECT_ID/hikma-health-backend:$COMMIT_SHA'
substitutions:
  _DB_INSTANCE: 'mmc-dppo:us-central1:dppo-hikma-db'
  _DB_NAME: 'hikma_prod'
options:
  machineType: 'E2_HIGHCPU_8'


